In [0]:
def test():
    print("Test() for function")
    return
test()  

Test() for function


In [0]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
   
obj=Demo()  
obj.test()

test() for the class and method


In [0]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
      
    def add(self,p1,p2):
        return p1+p2
    
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [0]:
class person(object):
    def __init__(self,name):
        self.name = name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
      
#derived class
class employee(person):
    def isemployee(self):
        return True

emp = person("Anil")
print(emp.getname(),emp.isemployee())

emp1 = employee("Akhil")
print(emp1.getname(),emp1.isemployee())

Anil False
Akhil True


Python Numpy

In [0]:
import numpy as np
lst=[1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [0]:
import numpy as np
lst=[1,2,3,4,5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [0]:
#Reshape of given array
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [0]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [0]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [0]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [33]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Slicing Column :",a1[:,1])

Slicing Column : [2 5]


In [34]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column :",a1[:,2])

Slicing Last Column : [3 6]


In [37]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])
print("second row :",a1[1])

first row : [1 2 3]
second row : [4 5 6]


In [39]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[4.33161595 3.27551541 5.20884495 3.35411331 3.32607882 4.3539515
 4.33540986 3.92588963 4.66149367 4.77637273]
Min value =  3.2755154088626615
Max value =  5.208844953205137
Mean value =  4.154928583484746
Median value =  4.333512902521311


In [40]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [50]:
import pandas as pd
dict = {"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
        "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com",
                   "harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
        "MobileNumber":[999,888,777,888,777,999],
        "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd
